/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef RUST_RUST_DEMO_MODULE_H
#define RUST_RUST_DEMO_MODULE_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

void rust_function(void);

void rust_periodic(void);

#endif /* RUST_RUST_DEMO_MODULE_H */

/* Text to put at the end of the generated file */
