################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
var/Microjet/sim/subsystems \
var/Microjet/sim/subsystems/sensors \
var/Microjet/sim/subsystems/radio_control \
var/Microjet/sim/subsystems/navigation \
var/Microjet/sim/subsystems/ins \
var/Microjet/sim/subsystems/gps \
var/Microjet/sim/subsystems/datalink \
var/Microjet/sim/subsystems/ahrs \
var/Microjet/sim \
var/Microjet/sim/modules/openlog \
var/Microjet/sim/modules/digital_cam \
var/Microjet/sim/mcu_periph \
var/Microjet/sim/math \
var/Microjet/sim/firmwares/fixedwing/stabilization \
var/Microjet/sim/firmwares/fixedwing \
var/Microjet/sim/firmwares/fixedwing/guidance \
var/Microjet/sim/arch/sim/subsystems \
var/Microjet/sim/arch/sim/subsystems/radio_control \
var/Microjet/sim/arch/sim \
var/Microjet/sim/arch/sim/mcu_periph \
var/ARDrone2/ap/subsystems \
var/ARDrone2/ap \
var/ARDrone2/ap/mcu_periph \
var/ARDrone2/ap/math \
var/ARDrone2/ap/firmwares/rotorcraft \
var/ARDrone2/ap/arch/ardrone2/subsystems \
var/ARDrone2/ap/arch/ardrone2/mcu_periph \
var/ARDrone2/ap/arch/ardrone2 \
sw/tools/wiki_gen \
sw/tools \
sw/simulator \
sw/simulator/scilab/q3d/fonts \
sw/simulator/old_booz/tests \
sw/simulator/old_booz \
sw/simulator/nps \
sw/logalizer \
sw/lib/ocaml \
sw/in_progress/wind_tunnel \
sw/in_progress/turbine \
sw/in_progress/satcom \
sw/in_progress/river_tracking/src \
sw/in_progress/rctx \
sw/in_progress/motor_bench \
sw/in_progress/maptests \
sw/in_progress/log_parser \
sw/in_progress/ir_usb_i2c \
sw/in_progress/ir_calibration \
sw/in_progress/inertial/C \
sw/in_progress/fdm \
sw/in_progress/button \
sw/ground_segment/tmtc \
sw/ground_segment/tmtc/GSM \
sw/ground_segment/multimon \
sw/ground_segment/modem \
sw/ground_segment/misc \
sw/ground_segment/lpc21iap \
sw/ground_segment/joystick \
sw/ground_segment/cockpit \
sw/ext/luftboot/src \
sw/ext/luftboot/examples/cdcacm \
sw/ext/luftboot/examples/blinky \
sw/ext/libopencm3/lib/usb \
sw/ext/libopencm3/lib/stm32 \
sw/ext/libopencm3/lib/stm32/l1 \
sw/ext/libopencm3/lib/stm32/f4 \
sw/ext/libopencm3/lib/stm32/f2 \
sw/ext/libopencm3/lib/stm32/f1 \
sw/ext/libopencm3/lib/lpc43xx \
sw/ext/libopencm3/lib/lpc17xx \
sw/ext/libopencm3/lib/lpc13xx \
sw/ext/libopencm3/lib/lm3s \
sw/ext/libopencm3/lib/efm32/efm32tg \
sw/ext/libopencm3/lib/efm32/efm32lg \
sw/ext/libopencm3/lib/efm32/efm32gg \
sw/ext/libopencm3/lib/efm32/efm32g \
sw/ext/libopencm3/lib/dispatch \
sw/ext/libopencm3/lib/cm3 \
sw/ext/libopencm3/examples/stm32/l1/stm32l-discovery/usart \
sw/ext/libopencm3/examples/stm32/l1/stm32l-discovery/miniblink \
sw/ext/libopencm3/examples/stm32/l1/stm32l-discovery/button-irq-printf \
sw/ext/libopencm3/examples/stm32/f4/stm32f4-discovery/usb_cdcacm \
sw/ext/libopencm3/examples/stm32/f4/stm32f4-discovery/usart \
sw/ext/libopencm3/examples/stm32/f4/stm32f4-discovery/random \
sw/ext/libopencm3/examples/stm32/f4/stm32f4-discovery/miniblink \
sw/ext/libopencm3/examples/stm32/f4/stm32f4-discovery/mandelbrot \
sw/ext/libopencm3/examples/stm32/f4/stm32f4-discovery/fancyblink \
sw/ext/libopencm3/examples/stm32/f4/stm32f4-discovery/button \
sw/ext/libopencm3/examples/stm32/f2/jobygps/usart_printf \
sw/ext/libopencm3/examples/stm32/f2/jobygps/spi_test \
sw/ext/libopencm3/examples/stm32/f2/jobygps/miniblink \
sw/ext/libopencm3/examples/stm32/f1/stm32vl-discovery/usart \
sw/ext/libopencm3/examples/stm32/f1/stm32vl-discovery/rtc \
sw/ext/libopencm3/examples/stm32/f1/stm32vl-discovery/miniblink \
sw/ext/libopencm3/examples/stm32/f1/stm32vl-discovery/fancyblink \
sw/ext/libopencm3/examples/stm32/f1/stm32vl-discovery/button \
sw/ext/libopencm3/examples/stm32/f1/stm32-h107/usb_simple \
sw/ext/libopencm3/examples/stm32/f1/stm32-h107/fancyblink \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usb_iap \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usb_hid \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usb_dfu \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usb_cdcacm \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usart_printf \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usart_irq_printf \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usart_irq \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/usart \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/traceswo \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/timer \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/spi \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/pwm_6step \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/miniblink \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/led_stripe \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/fancyblink \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/exti_rising_falling \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/exti_both \
sw/ext/libopencm3/examples/stm32/f1/stm32-h103/button \
sw/ext/libopencm3/examples/stm32/f1/other/usb_hid \
sw/ext/libopencm3/examples/stm32/f1/other/usb_dfu \
sw/ext/libopencm3/examples/stm32/f1/other/usb_cdcacm \
sw/ext/libopencm3/examples/stm32/f1/other/timer_interrupt \
sw/ext/libopencm3/examples/stm32/f1/other/systick \
sw/ext/libopencm3/examples/stm32/f1/other/rtc \
sw/ext/libopencm3/examples/stm32/f1/other/i2c_stts75_sensor \
sw/ext/libopencm3/examples/stm32/f1/other/dogm128 \
sw/ext/libopencm3/examples/stm32/f1/other/dma_mem2mem \
sw/ext/libopencm3/examples/stm32/f1/other/adc_temperature_sensor \
sw/ext/libopencm3/examples/stm32/f1/obldc/usart_irq \
sw/ext/libopencm3/examples/stm32/f1/obldc/usart \
sw/ext/libopencm3/examples/stm32/f1/obldc/systick \
sw/ext/libopencm3/examples/stm32/f1/obldc/pwmleds \
sw/ext/libopencm3/examples/stm32/f1/obldc/led \
sw/ext/libopencm3/examples/stm32/f1/obldc/can \
sw/ext/libopencm3/examples/stm32/f1/mb525/pwmleds \
sw/ext/libopencm3/examples/stm32/f1/mb525/fancyblink \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/usart_printf \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/usart_irq_printf \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/usart_irq \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/usart_dma \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/usart \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/fancyblink \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/adc_regular \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/adc_injec_timtrig_irq_4ch \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/adc_injec_timtrig_irq \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/adc_injec_timtrig \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-2/adc_injec \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-1/usb_hid \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-1/usb_dfu \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-1/usb_cdcacm \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-1/fancyblink \
sw/ext/libopencm3/examples/stm32/f1/lisa-m-1/can \
sw/ext/libopencm3/examples/lpc43xx/hackrf-jellybean/systick \
sw/ext/libopencm3/examples/lpc43xx/hackrf-jellybean/ssp \
sw/ext/libopencm3/examples/lpc43xx/hackrf-jellybean/miniblink_rom_to_ram \
sw/ext/libopencm3/examples/lpc43xx/hackrf-jellybean/miniblink \
sw/ext/libopencm3/examples/lpc43xx/hackrf-jellybean/i2c \
sw/ext/libopencm3/examples/lpc43xx/diolan-lpc-4350-db1/miniblink \
sw/ext/libopencm3/examples/lpc17xx/blueboard-lpc1768-h/miniblink \
sw/ext/libopencm3/examples/lpc13xx/lpc-p1343/miniblink \
sw/ext/libopencm3/examples/lm3s/lm3s3748-evb/miniblink \
sw/airborne/test \
sw/airborne/test/subsystems \
sw/airborne/test/peripherals \
sw/airborne/test/mcu_periph \
sw/airborne/test/ahrs \
sw/airborne/subsystems \
sw/airborne/subsystems/sensors \
sw/airborne/subsystems/radio_control \
sw/airborne/subsystems/navigation \
sw/airborne/subsystems/ins \
sw/airborne/subsystems/imu \
sw/airborne/subsystems/gps \
sw/airborne/subsystems/datalink \
sw/airborne/subsystems/ahrs \
sw/airborne/subsystems/actuators \
sw/airborne \
sw/airborne/sd_card \
sw/airborne/peripherals \
sw/airborne/modules/vehicle_interface \
sw/airborne/modules/sonar \
sw/airborne/modules/servo_switch \
sw/airborne/modules/sensors \
sw/airborne/modules/poles \
sw/airborne/modules/openlog \
sw/airborne/modules/nav \
sw/airborne/modules/multi \
sw/airborne/modules/meteo \
sw/airborne/modules/max3100 \
sw/airborne/modules/light \
sw/airborne/modules/led_safety_status \
sw/airborne/modules/ins \
sw/airborne/modules/gsm \
sw/airborne/modules/gps_i2c \
sw/airborne/modules/gps \
sw/airborne/modules/geo_mag \
sw/airborne/modules/enose \
sw/airborne/modules/display \
sw/airborne/modules/digital_cam \
sw/airborne/modules/deploy_sonar_buoy \
sw/airborne/modules/demo_module \
sw/airborne/modules/datalink \
sw/airborne/modules/core \
sw/airborne/modules/com \
sw/airborne/modules/cartography \
sw/airborne/modules/cam_control \
sw/airborne/modules/benchmark \
sw/airborne/modules/bat_checker \
sw/airborne/modules/airborne_ant_track \
sw/airborne/modules/adcs \
sw/airborne/modules/MPPT \
sw/airborne/mcu_periph \
sw/airborne/math \
sw/airborne/lisa \
sw/airborne/lisa/test \
sw/airborne/lisa/arch/stm32 \
sw/airborne/fms \
sw/airborne/fms/libeknav \
sw/airborne/firmwares/wind_tunnel \
sw/airborne/firmwares/vor \
sw/airborne/firmwares/tutorial \
sw/airborne/firmwares/setup \
sw/airborne/firmwares/rotorcraft \
sw/airborne/firmwares/rotorcraft/stabilization \
sw/airborne/firmwares/rotorcraft/guidance \
sw/airborne/firmwares/non_ap/led_flasher \
sw/airborne/firmwares/non_ap/geiger_counter \
sw/airborne/firmwares/motor_bench \
sw/airborne/firmwares/logger \
sw/airborne/firmwares/fixedwing/stabilization \
sw/airborne/firmwares/fixedwing \
sw/airborne/firmwares/fixedwing/guidance \
sw/airborne/firmwares/beth \
sw/airborne/booz/test \
sw/airborne/boards/umarim \
sw/airborne/boards/pc \
sw/airborne/boards/navgo \
sw/airborne/boards/lisa_m \
sw/airborne/boards/lisa_l \
sw/airborne/boards/booz \
sw/airborne/boards/ardrone \
sw/airborne/arch/stm32/subsystems \
sw/airborne/arch/stm32/subsystems/radio_control \
sw/airborne/arch/stm32/subsystems/imu \
sw/airborne/arch/stm32/subsystems/actuators \
sw/airborne/arch/stm32/peripherals \
sw/airborne/arch/stm32/mcu_periph \
sw/airborne/arch/stm32/mcu_periph/obsolete \
sw/airborne/arch/stm32 \
sw/airborne/arch/sim/subsystems \
sw/airborne/arch/sim/subsystems/radio_control \
sw/airborne/arch/sim/subsystems/imu \
sw/airborne/arch/sim/subsystems/actuators \
sw/airborne/arch/sim \
sw/airborne/arch/sim/peripherals \
sw/airborne/arch/sim/modules/ins \
sw/airborne/arch/sim/modules/enose \
sw/airborne/arch/sim/modules/core \
sw/airborne/arch/sim/mcu_periph \
sw/airborne/arch/omap/mcu_periph \
sw/airborne/arch/lpc21 \
sw/airborne/arch/lpc21/test \
sw/airborne/arch/lpc21/test/bootloader \
sw/airborne/arch/lpc21/subsystems \
sw/airborne/arch/lpc21/subsystems/radio_control \
sw/airborne/arch/lpc21/subsystems/imu \
sw/airborne/arch/lpc21/subsystems/datalink \
sw/airborne/arch/lpc21/subsystems/actuators \
sw/airborne/arch/lpc21/peripherals \
sw/airborne/arch/lpc21/modules/sensors \
sw/airborne/arch/lpc21/modules/display \
sw/airborne/arch/lpc21/modules/core \
sw/airborne/arch/lpc21/modules/adcs \
sw/airborne/arch/lpc21/mcu_periph \
sw/airborne/arch/lpc21/lpcusb \
sw/airborne/arch/lpc21/lpcusb/examples \
sw/airborne/arch/lpc21/efsl/src \
sw/airborne/arch/lpc21/efsl/src/interfaces \
sw/airborne/arch/avr \
sw/airborne/arch/avr/subsystems/datalink \
sw/airborne/arch/avr/mcu_periph \
sw/airborne/arch/ardrone2/subsystems \
sw/airborne/arch/ardrone2/subsystems/radio_control \
sw/airborne/arch/ardrone2/subsystems/imu \
sw/airborne/arch/ardrone2/subsystems/actuators \
sw/airborne/arch/ardrone2/peripherals \
sw/airborne/arch/ardrone2/mcu_periph \
sw/airborne/arch/ardrone2/mcu_periph/obsolete \
sw/airborne/arch/ardrone2 \
conf/gps \

