


SRC_BOOZ=booz
SRC_BOOZ_ARCH=$(SRC_BOOZ)/arch/$(ARCH)
SRC_BOOZ_TEST=$(SRC_BOOZ)/test

SRC_BOOZ_PRIV=booz_priv

CFG_BOOZ=$(PAPARAZZI_SRC)/conf/firmwares/

BOOZ_INC = -I$(SRC_BOOZ) -I$(SRC_BOOZ_ARCH)
