# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_module_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateModule_Window(object):
    def setupUi(self, CreateModule_Window):
        CreateModule_Window.setObjectName("CreateModule_Window")
        CreateModule_Window.resize(875, 553)
        self.centralwidget = QtWidgets.QWidget(CreateModule_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout.addWidget(self.name_edit)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.directory_combo = QtWidgets.QComboBox(self.centralwidget)
        self.directory_combo.setEditable(True)
        self.directory_combo.setObjectName("directory_combo")
        self.horizontalLayout_2.addWidget(self.directory_combo)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.licence_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.licence_comboBox.setEditable(False)
        self.licence_comboBox.setObjectName("licence_comboBox")
        self.licence_comboBox.addItem("")
        self.licence_comboBox.addItem("")
        self.horizontalLayout_15.addWidget(self.licence_comboBox)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.author_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.author_edit.setObjectName("author_edit")
        self.horizontalLayout_4.addWidget(self.author_edit)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.email_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.email_edit.setObjectName("email_edit")
        self.horizontalLayout_3.addWidget(self.email_edit)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.description_edit = QtWidgets.QPlainTextEdit(self.splitter)
        self.description_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.description_edit.setBaseSize(QtCore.QSize(0, 30))
        self.description_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.description_edit.setObjectName("description_edit")
        self.components_area = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.components_area.sizePolicy().hasHeightForWidth())
        self.components_area.setSizePolicy(sizePolicy)
        self.components_area.setWidgetResizable(True)
        self.components_area.setObjectName("components_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 855, 258))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scroll_area_layout.setObjectName("scroll_area_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 76, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.scroll_area_layout.addItem(spacerItem)
        self.components_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.components_combo = QtWidgets.QComboBox(self.centralwidget)
        self.components_combo.setObjectName("components_combo")
        self.components_combo.addItem("")
        self.components_combo.addItem("")
        self.components_combo.addItem("")
        self.components_combo.addItem("")
        self.horizontalLayout_7.addWidget(self.components_combo)
        self.component_add_button = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.component_add_button.setIcon(icon)
        self.component_add_button.setObjectName("component_add_button")
        self.horizontalLayout_7.addWidget(self.component_add_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setObjectName("create_button")
        self.verticalLayout.addWidget(self.create_button)
        CreateModule_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateModule_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 22))
        self.menubar.setObjectName("menubar")
        CreateModule_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateModule_Window)
        self.statusbar.setObjectName("statusbar")
        CreateModule_Window.setStatusBar(self.statusbar)

        self.retranslateUi(CreateModule_Window)
        QtCore.QMetaObject.connectSlotsByName(CreateModule_Window)

    def retranslateUi(self, CreateModule_Window):
        _translate = QtCore.QCoreApplication.translate
        CreateModule_Window.setWindowTitle(_translate("CreateModule_Window", "Create Module"))
        self.label.setText(_translate("CreateModule_Window", "Module name"))
        self.label_2.setText(_translate("CreateModule_Window", "Directory"))
        self.label_12.setText(_translate("CreateModule_Window", "Licence"))
        self.licence_comboBox.setItemText(0, _translate("CreateModule_Window", "GPLv2"))
        self.licence_comboBox.setItemText(1, _translate("CreateModule_Window", "None"))
        self.label_4.setText(_translate("CreateModule_Window", "Author"))
        self.label_5.setText(_translate("CreateModule_Window", "email"))
        self.label_3.setText(_translate("CreateModule_Window", "Description"))
        self.label_6.setText(_translate("CreateModule_Window", "Add element :"))
        self.components_combo.setItemText(0, _translate("CreateModule_Window", "Init"))
        self.components_combo.setItemText(1, _translate("CreateModule_Window", "Periodic"))
        self.components_combo.setItemText(2, _translate("CreateModule_Window", "Event"))
        self.components_combo.setItemText(3, _translate("CreateModule_Window", "Datalink"))
        self.component_add_button.setToolTip(_translate("CreateModule_Window", "Add component"))
        self.component_add_button.setText(_translate("CreateModule_Window", "Add"))
        self.create_button.setText(_translate("CreateModule_Window", "Create Module"))

