all:
	pyuic5 create_module_ui.ui -o create_module_ui.py
	pyuic5 datalink_ui.ui -o datalink_ui.py
	pyuic5 event_ui.ui -o event_ui.py
	pyuic5 init_ui.ui -o init_ui.py
	pyuic5 periodic_ui.ui -o periodic_ui.py

clean:
	rm create_module_ui.py datalink_ui.py event_ui.py init_ui.py periodic_ui.py

