
IMU_NAVGO_CFLAGS  = -DUSE_IMU
IMU_NAVGO_CFLAGS += -DIMU_TYPE_H=\"boards/navgo/imu_navgo.h\"

IMU_NAVGO_SRCS    = $(SRC_SUBSYSTEMS)/imu.c             \
                    $(SRC_BOARD)/imu_navgo.c

IMU_NAVGO_CFLAGS += -DHMC58XX_I2C_DEVICE=i2c1
IMU_NAVGO_SRCS += peripherals/hmc58xx.c

IMU_NAVGO_CFLAGS += -DUSE_I2C
IMU_NAVGO_CFLAGS += -DUSE_I2C1
IMU_NAVGO_CFLAGS += -DIMU_NAVGO_I2C_DEVICE=i2c1

ap.CFLAGS += $(IMU_NAVGO_CFLAGS)
ap.srcs   += $(IMU_NAVGO_SRCS)

