#! /bin/sh
mkdir -p $HOME/paparazzi
cp -a /usr/share/paparazzi/var $HOME/paparazzi
cp -a /usr/share/paparazzi/conf $HOME/paparazzi
cp -a /usr/share/paparazzi/data $HOME/paparazzi
PATH=$PATH:/usr/share/paparazzi/bin
cockpit.pl &
sleep 1
map2d -m muret_UTM.xml &
sleep 1
$HOME/paparazzi/var/Thon1/sim/simsitl &
sleep 1
$HOME/paparazzi/var/Thon2/sim/simsitl &
sleep 1
receive
