[package]
name = "key_generator"
version = "0.1.0"
authors = ["Michal Podhradsky <michal.podhradsky@galois.com>"]

[dependencies]
rusthacl = { git = "https://github.com/podhrmic/rusthacl" }
rand = "0.3"