void glActiveTexture(void) { return; }
void glAlphaFunc(void) { return; }
void glAlphaFuncx(void) { return; }
void glBindBuffer(void) { return; }
void glBindTexture(void) { return; }
void glBlendFunc(void) { return; }
void glBufferData(void) { return; }
void glBufferSubData(void) { return; }
void glClear(void) { return; }
void glClearColor(void) { return; }
void glClearColorx(void) { return; }
void glClearDepthf(void) { return; }
void glClearDepthx(void) { return; }
void glClearStencil(void) { return; }
void glClientActiveTexture(void) { return; }
void glClipPlanef(void) { return; }
void glClipPlanex(void) { return; }
void glColor4f(void) { return; }
void glColor4ub(void) { return; }
void glColor4x(void) { return; }
void glColorMask(void) { return; }
void glColorPointer(void) { return; }
void glCompressedTexImage2D(void) { return; }
void glCompressedTexSubImage2D(void) { return; }
void glCopyTexImage2D(void) { return; }
void glCopyTexSubImage2D(void) { return; }
void glCullFace(void) { return; }
void glCurrentPaletteMatrixOES(void) { return; }
void glDeleteBuffers(void) { return; }
void glDeleteTextures(void) { return; }
void glDepthFunc(void) { return; }
void glDepthMask(void) { return; }
void glDepthRangef(void) { return; }
void glDepthRangex(void) { return; }
void glDisable(void) { return; }
void glDisableClientState(void) { return; }
void glDrawArrays(void) { return; }
void glDrawElements(void) { return; }
void glEGLImageTargetRenderbufferStorageOES(void) { return; }
void glEGLImageTargetTexture2DOES(void) { return; }
void glEnable(void) { return; }
void glEnableClientState(void) { return; }
void glFinish(void) { return; }
void glFlush(void) { return; }
void glFogf(void) { return; }
void glFogfv(void) { return; }
void glFogx(void) { return; }
void glFogxv(void) { return; }
void glFrontFace(void) { return; }
void glFrustumf(void) { return; }
void glFrustumx(void) { return; }
void glGenBuffers(void) { return; }
void glGenTextures(void) { return; }
void glGetBooleanv(void) { return; }
void glGetBufferParameteriv(void) { return; }
void glGetClipPlanef(void) { return; }
void glGetClipPlanex(void) { return; }
void glGetError(void) { return; }
void glGetFixedv(void) { return; }
void glGetFloatv(void) { return; }
void glGetIntegerv(void) { return; }
void glGetLightfv(void) { return; }
void glGetLightxv(void) { return; }
void glGetMaterialfv(void) { return; }
void glGetMaterialxv(void) { return; }
void glGetPointerv(void) { return; }
void glGetString(void) { return; }
void glGetTexEnvfv(void) { return; }
void glGetTexEnviv(void) { return; }
void glGetTexEnvxv(void) { return; }
void glGetTexParameterfv(void) { return; }
void glGetTexParameteriv(void) { return; }
void glGetTexParameterxv(void) { return; }
void glHint(void) { return; }
void glIsBuffer(void) { return; }
void glIsEnabled(void) { return; }
void glIsTexture(void) { return; }
void glLightModelf(void) { return; }
void glLightModelfv(void) { return; }
void glLightModelx(void) { return; }
void glLightModelxv(void) { return; }
void glLightf(void) { return; }
void glLightfv(void) { return; }
void glLightx(void) { return; }
void glLightxv(void) { return; }
void glLineWidth(void) { return; }
void glLineWidthx(void) { return; }
void glLoadIdentity(void) { return; }
void glLoadMatrixf(void) { return; }
void glLoadMatrixx(void) { return; }
void glLoadPaletteFromModelViewMatrixOES(void) { return; }
void glLogicOp(void) { return; }
void glMaterialf(void) { return; }
void glMaterialfv(void) { return; }
void glMaterialx(void) { return; }
void glMaterialxv(void) { return; }
void glMatrixIndexPointerOES(void) { return; }
void glMatrixMode(void) { return; }
void glMultMatrixf(void) { return; }
void glMultMatrixx(void) { return; }
void glMultiTexCoord4f(void) { return; }
void glMultiTexCoord4x(void) { return; }
void glNormal3f(void) { return; }
void glNormal3x(void) { return; }
void glNormalPointer(void) { return; }
void glOrthof(void) { return; }
void glOrthox(void) { return; }
void glPixelStorei(void) { return; }
void glPointParameterf(void) { return; }
void glPointParameterfv(void) { return; }
void glPointParameterx(void) { return; }
void glPointParameterxv(void) { return; }
void glPointSize(void) { return; }
void glPointSizePointerOES(void) { return; }
void glPointSizex(void) { return; }
void glPolygonOffset(void) { return; }
void glPolygonOffsetx(void) { return; }
void glPopMatrix(void) { return; }
void glPushMatrix(void) { return; }
void glQueryMatrixxOES(void) { return; }
void glReadPixels(void) { return; }
void glRotatef(void) { return; }
void glRotatex(void) { return; }
void glSampleCoverage(void) { return; }
void glSampleCoveragex(void) { return; }
void glScalef(void) { return; }
void glScalex(void) { return; }
void glScissor(void) { return; }
void glShadeModel(void) { return; }
void glStencilFunc(void) { return; }
void glStencilMask(void) { return; }
void glStencilOp(void) { return; }
void glTexCoordPointer(void) { return; }
void glTexEnvf(void) { return; }
void glTexEnvfv(void) { return; }
void glTexEnvi(void) { return; }
void glTexEnviv(void) { return; }
void glTexEnvx(void) { return; }
void glTexEnvxv(void) { return; }
void glTexImage2D(void) { return; }
void glTexParameterf(void) { return; }
void glTexParameterfv(void) { return; }
void glTexParameteri(void) { return; }
void glTexParameteriv(void) { return; }
void glTexParameterx(void) { return; }
void glTexParameterxv(void) { return; }
void glTexSubImage2D(void) { return; }
void glTranslatef(void) { return; }
void glTranslatex(void) { return; }
void glVertexPointer(void) { return; }
void glViewport(void) { return; }
void glWeightPointerOES(void) { return; }
