void glActiveTexture(void) { return; }
void glAttachShader(void) { return; }
void glBindAttribLocation(void) { return; }
void glBindBuffer(void) { return; }
void glBindFramebuffer(void) { return; }
void glBindRenderbuffer(void) { return; }
void glBindTexture(void) { return; }
void glBlendColor(void) { return; }
void glBlendEquation(void) { return; }
void glBlendEquationSeparate(void) { return; }
void glBlendFunc(void) { return; }
void glBlendFuncSeparate(void) { return; }
void glBufferData(void) { return; }
void glBufferSubData(void) { return; }
void glCheckFramebufferStatus(void) { return; }
void glClear(void) { return; }
void glClearColor(void) { return; }
void glClearDepthf(void) { return; }
void glClearStencil(void) { return; }
void glColorMask(void) { return; }
void glCompileShader(void) { return; }
void glCompressedTexImage2D(void) { return; }
void glCompressedTexSubImage2D(void) { return; }
void glCopyTexImage2D(void) { return; }
void glCopyTexSubImage2D(void) { return; }
void glCreateProgram(void) { return; }
void glCreateShader(void) { return; }
void glCullFace(void) { return; }
void glDeleteBuffers(void) { return; }
void glDeleteFramebuffers(void) { return; }
void glDeleteProgram(void) { return; }
void glDeleteRenderbuffers(void) { return; }
void glDeleteShader(void) { return; }
void glDeleteTextures(void) { return; }
void glDepthFunc(void) { return; }
void glDepthMask(void) { return; }
void glDepthRangef(void) { return; }
void glDetachShader(void) { return; }
void glDisable(void) { return; }
void glDisableVertexAttribArray(void) { return; }
void glDrawArrays(void) { return; }
void glDrawElements(void) { return; }
void glEnable(void) { return; }
void glEnableVertexAttribArray(void) { return; }
void glFinish(void) { return; }
void glFlush(void) { return; }
void glFramebufferRenderbuffer(void) { return; }
void glFramebufferTexture2D(void) { return; }
void glFrontFace(void) { return; }
void glGenBuffers(void) { return; }
void glGenerateMipmap(void) { return; }
void glGenFramebuffers(void) { return; }
void glGenRenderbuffers(void) { return; }
void glGenTextures(void) { return; }
void glGetActiveAttrib(void) { return; }
void glGetActiveUniform(void) { return; }
void glGetAttachedShaders(void) { return; }
void glGetAttribLocation(void) { return; }
void glGetBooleanv(void) { return; }
void glGetBufferParameteriv(void) { return; }
void glGetError(void) { return; }
void glGetFloatv(void) { return; }
void glGetFramebufferAttachmentParameteriv(void) { return; }
void glGetIntegerv(void) { return; }
void glGetProgramiv(void) { return; }
void glGetProgramInfoLog(void) { return; }
void glGetRenderbufferParameteriv(void) { return; }
void glGetShaderiv(void) { return; }
void glGetShaderInfoLog(void) { return; }
void glGetShaderPrecisionFormat(void) { return; }
void glGetShaderSource(void) { return; }
void glGetString(void) { return; }
void glGetTexParameterfv(void) { return; }
void glGetTexParameteriv(void) { return; }
void glGetUniformfv(void) { return; }
void glGetUniformiv(void) { return; }
void glGetUniformLocation(void) { return; }
void glGetVertexAttribfv(void) { return; }
void glGetVertexAttribiv(void) { return; }
void glGetVertexAttribPointerv(void) { return; }
void glHint(void) { return; }
void glIsBuffer(void) { return; }
void glIsEnabled(void) { return; }
void glIsFramebuffer(void) { return; }
void glIsProgram(void) { return; }
void glIsRenderbuffer(void) { return; }
void glIsShader(void) { return; }
void glIsTexture(void) { return; }
void glLineWidth(void) { return; }
void glLinkProgram(void) { return; }
void glPixelStorei(void) { return; }
void glPolygonOffset(void) { return; }
void glReadPixels(void) { return; }
void glReleaseShaderCompiler(void) { return; }
void glRenderbufferStorage(void) { return; }
void glSampleCoverage(void) { return; }
void glScissor(void) { return; }
void glShaderBinary(void) { return; }
void glShaderSource(void) { return; }
void glStencilFunc(void) { return; }
void glStencilFuncSeparate(void) { return; }
void glStencilMask(void) { return; }
void glStencilMaskSeparate(void) { return; }
void glStencilOp(void) { return; }
void glStencilOpSeparate(void) { return; }
void glTexImage2D(void) { return; }
void glTexParameterf(void) { return; }
void glTexParameterfv(void) { return; }
void glTexParameteri(void) { return; }
void glTexParameteriv(void) { return; }
void glTexSubImage2D(void) { return; }
void glUniform1f(void) { return; }
void glUniform1fv(void) { return; }
void glUniform1i(void) { return; }
void glUniform1iv(void) { return; }
void glUniform2f(void) { return; }
void glUniform2fv(void) { return; }
void glUniform2i(void) { return; }
void glUniform2iv(void) { return; }
void glUniform3f(void) { return; }
void glUniform3fv(void) { return; }
void glUniform3i(void) { return; }
void glUniform3iv(void) { return; }
void glUniform4f(void) { return; }
void glUniform4fv(void) { return; }
void glUniform4i(void) { return; }
void glUniform4iv(void) { return; }
void glUniformMatrix2fv(void) { return; }
void glUniformMatrix3fv(void) { return; }
void glUniformMatrix4fv(void) { return; }
void glUseProgram(void) { return; }
void glValidateProgram(void) { return; }
void glVertexAttrib1f(void) { return; }
void glVertexAttrib1fv(void) { return; }
void glVertexAttrib2f(void) { return; }
void glVertexAttrib2fv(void) { return; }
void glVertexAttrib3f(void) { return; }
void glVertexAttrib3fv(void) { return; }
void glVertexAttrib4f(void) { return; }
void glVertexAttrib4fv(void) { return; }
void glVertexAttribPointer(void) { return; }
void glViewport(void) { return; }

/* OpenGL ES 3.0 */

void glReadBuffer(void) { return; }
void glDrawRangeElements(void) { return; }
void glTexImage3D(void) { return; }
void glTexSubImage3D(void) { return; }
void glCopyTexSubImage3D(void) { return; }
void glCompressedTexImage3D(void) { return; }
void glCompressedTexSubImage3D(void) { return; }
void glGenQueries(void) { return; }
void glDeleteQueries(void) { return; }
void glIsQuery(void) { return; }
void glBeginQuery(void) { return; }
void glEndQuery(void) { return; }
void glGetQueryiv(void) { return; }
void glGetQueryObjectuiv(void) { return; }
void glUnmapBuffer(void) { return; }
void glGetBufferPointerv(void) { return; }
void glDrawBuffers(void) { return; }
void glUniformMatrix2x3fv(void) { return; }
void glUniformMatrix3x2fv(void) { return; }
void glUniformMatrix2x4fv(void) { return; }
void glUniformMatrix4x2fv(void) { return; }
void glUniformMatrix3x4fv(void) { return; }
void glUniformMatrix4x3fv(void) { return; }
void glBlitFramebuffer(void) { return; }
void glRenderbufferStorageMultisample(void) { return; }
void glFramebufferTextureLayer(void) { return; }
void glMapBufferRange(void) { return; }
void glFlushMappedBufferRange(void) { return; }
void glBindVertexArray(void) { return; }
void glDeleteVertexArrays(void) { return; }
void glGenVertexArrays(void) { return; }
void glIsVertexArray(void) { return; }
void glGetIntegeri_v(void) { return; }
void glBeginTransformFeedback(void) { return; }
void glEndTransformFeedback(void) { return; }
void glBindBufferRange(void) { return; }
void glBindBufferBase(void) { return; }
void glTransformFeedbackVaryings(void) { return; }
void glGetTransformFeedbackVarying(void) { return; }
void glVertexAttribIPointer(void) { return; }
void glGetVertexAttribIiv(void) { return; }
void glGetVertexAttribIuiv(void) { return; }
void glVertexAttribI4i(void) { return; }
void glVertexAttribI4ui(void) { return; }
void glVertexAttribI4iv(void) { return; }
void glVertexAttribI4uiv(void) { return; }
void glGetUniformuiv(void) { return; }
void glGetFragDataLocation(void) { return; }
void glUniform1ui(void) { return; }
void glUniform2ui(void) { return; }
void glUniform3ui(void) { return; }
void glUniform4ui(void) { return; }
void glUniform1uiv(void) { return; }
void glUniform2uiv(void) { return; }
void glUniform3uiv(void) { return; }
void glUniform4uiv(void) { return; }
void glClearBufferiv(void) { return; }
void glClearBufferuiv(void) { return; }
void glClearBufferfv(void) { return; }
void glClearBufferfi(void) { return; }
void glGetStringi(void) { return; }
void glCopyBufferSubData(void) { return; }
void glGetUniformIndices(void) { return; }
void glGetActiveUniformsiv(void) { return; }
void glGetUniformBlockIndex(void) { return; }
void glGetActiveUniformBlockiv(void) { return; }
void glGetActiveUniformBlockName(void) { return; }
void glUniformBlockBinding(void) { return; }
void glDrawArraysInstanced(void) { return; }
void glDrawElementsInstanced(void) { return; }
void glFenceSync(void) { return; }
void glIsSync(void) { return; }
void glDeleteSync(void) { return; }
void glClientWaitSync(void) { return; }
void glWaitSync(void) { return; }
void glGetInteger64v(void) { return; }
void glGetSynciv(void) { return; }
void glGetInteger64i_v(void) { return; }
void glGetBufferParameteri64v(void) { return; }
void glGenSamplers(void) { return; }
void glDeleteSamplers(void) { return; }
void glIsSampler(void) { return; }
void glBindSampler(void) { return; }
void glSamplerParameteri(void) { return; }
void glSamplerParameteriv(void) { return; }
void glSamplerParameterf(void) { return; }
void glSamplerParameterfv(void) { return; }
void glGetSamplerParameteriv(void) { return; }
void glGetSamplerParameterfv(void) { return; }
void glVertexAttribDivisor(void) { return; }
void glBindTransformFeedback(void) { return; }
void glDeleteTransformFeedbacks(void) { return; }
void glGenTransformFeedbacks(void) { return; }
void glIsTransformFeedback(void) { return; }
void glPauseTransformFeedback(void) { return; }
void glResumeTransformFeedback(void) { return; }
void glGetProgramBinary(void) { return; }
void glProgramBinary(void) { return; }
void glProgramParameteri(void) { return; }
void glInvalidateFramebuffer(void) { return; }
void glInvalidateSubFramebuffer(void) { return; }
void glTexStorage2D(void) { return; }
void glTexStorage3D(void) { return; }
void glGetInternalformativ(void) { return; }

/* OpenGL ES 3.1, incomplete */

void glProgramUniform1ui(void) { return; }
void glDispatchCompute(void) { return; }
void glMemoryBarrier(void) { return; }
void glBindImageTexture(void) { return; }
void glProgramUniformMatrix4fv(void) { return; }
void glProgramUniform1f(void) { return; }
void glProgramUniform2f(void) { return; }
void glProgramUniform3f(void) { return; }
void glProgramUniform3fv(void) { return; }
void glProgramUniform4f(void) { return; }
void glDrawElementsIndirect(void) { return; }


