/*
 * $Id$
 *
 * Copyright (C) 2003-2006  Haiyang Chao
 *
 * This file is part of paparazzi.
 *
 * paparazzi is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * paparazzi is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with paparazzi; see the file COPYING.  If not, write to
 * the Free Software Foundation, 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 */

/** \file osam_imu_ugear.h
 *  \brief Communication with any IMU through serial communication (originally gps uart)
 * This file is first generated by Haiyang Chao on 20080507 for communication.
 */

#include "std.h"

void ugear_init( void );
void parse_ugear(uint8_t c);
void parse_ugear_msg( void );
void ugear_event( void );

#define __UgearLink(dev, _x) dev##_x
#define _UgearLink(dev, _x)  __UgearLink(dev, _x)
#define UgearLink(_x) _UgearLink(UGEAR_LINK, _x)

#define UgearBuffer() UgearLink(ChAvailable())
#define ReadUgearBuffer() { while (UgearLink(ChAvailable())&&!ugear_msg_received) parse_ugear(UgearLink(Getch())); }

#ifdef UGEAR_LED
#define UgearToggleLed() LED_TOGGLE(UGEAR_LED)
#else
#define UgearToggleLed() {}
#endif

#define UGEAR_MAX_PAYLOAD 40
/*#define UGEAR_MAX_PAYLOAD 24*/ /*Bugs!!! why work for the former version ??20080708*/
/*#define GPS_NB_CHANNELS 16*/

#define UGEAR_NAV_POSLLH_LAT(_ubx_payload) (int32_t)(*((uint8_t*)_ubx_payload+4)|*((uint8_t*)_ubx_payload+1+4)<<8|((int32_t)*((uint8_t*)_ubx_payload+2+4))<<16|((int32_t)*((uint8_t*)_ubx_payload+3+4))<<24)
#define UGEAR_NAV_POSLLH_LON(_ubx_payload) (int32_t)(*((uint8_t*)_ubx_payload)|*((uint8_t*)_ubx_payload+1)<<8|((int32_t)*((uint8_t*)_ubx_payload+2))<<16|((int32_t)*((uint8_t*)_ubx_payload+3))<<24)
#define UGEAR_NAV_POSLLH_HEIGHT(_ubx_payload) (int32_t)(*((uint8_t*)_ubx_payload+8)|*((uint8_t*)_ubx_payload+1+8)<<8|((int32_t)*((uint8_t*)_ubx_payload+2+8))<<16|((int32_t)*((uint8_t*)_ubx_payload+3+8))<<24)
#define UGEAR_NAV_POSLLH_VD(_ubx_payload) (int32_t)(*((uint8_t*)_ubx_payload+12)|*((uint8_t*)_ubx_payload+1+12)<<8|((int32_t)*((uint8_t*)_ubx_payload+2+12))<<16|((int32_t)*((uint8_t*)_ubx_payload+3+12))<<24)
#define UGEAR_NAV_VELNED_Heading(_ubx_payload) (int32_t)(*((uint8_t*)_ubx_payload+16)|*((uint8_t*)_ubx_payload+1+16)<<8|((int32_t)*((uint8_t*)_ubx_payload+2+16))<<16|((int32_t)*((uint8_t*)_ubx_payload+3+16))<<24)
#define UGEAR_NAV_SOL_Pacc(_ubx_payload) (uint32_t)(*((uint8_t*)_ubx_payload+20)|*((uint8_t*)_ubx_payload+1+20)<<8|((uint32_t)*((uint8_t*)_ubx_payload+2+20))<<16|((uint32_t)*((uint8_t*)_ubx_payload+3+20))<<24)
#define UGEAR_NAV_SOL_Sacc(_ubx_payload) (uint32_t)(*((uint8_t*)_ubx_payload+24)|*((uint8_t*)_ubx_payload+1+24)<<8|((uint32_t)*((uint8_t*)_ubx_payload+2+24))<<16|((uint32_t)*((uint8_t*)_ubx_payload+3+24))<<24)
#define UGEAR_NAV_VELNED_GSpeed(_ubx_payload) (uint32_t)(*((uint8_t*)_ubx_payload+28)|*((uint8_t*)_ubx_payload+1+28)<<8|((uint32_t)*((uint8_t*)_ubx_payload+2+28))<<16|((uint32_t)*((uint8_t*)_ubx_payload+3+28))<<24)
#define UGEAR_NAV_VELNED_ITOW(_ubx_payload) (uint32_t)(*((uint8_t*)_ubx_payload+32)|*((uint8_t*)_ubx_payload+1+32)<<8|((uint32_t)*((uint8_t*)_ubx_payload+2+32))<<16|((uint32_t)*((uint8_t*)_ubx_payload+3+32))<<24)
#define UGEAR_NAV_SOL_PDOP(_ubx_payload) (uint16_t)(*((uint8_t*)_ubx_payload+36)|*((uint8_t*)_ubx_payload+1+36)<<8)
#define UGEAR_NAV_SOL_numSV(_ubx_payload) (uint8_t)(*((uint8_t*)_ubx_payload+38))
#define UGEAR_IMU_PHI(_ubx_payload) (int16_t)(*((uint8_t*)_ubx_payload)|*((uint8_t*)_ubx_payload+1)<<8)
#define UGEAR_IMU_THE(_ubx_payload) (int16_t)(*((uint8_t*)_ubx_payload+2)|*((uint8_t*)_ubx_payload+1+2)<<8)
#define UGEAR_IMU_PSI(_ubx_payload) (int16_t)(*((uint8_t*)_ubx_payload+4)|*((uint8_t*)_ubx_payload+1+4)<<8)

extern volatile uint8_t ugear_msg_received;

/* variable defined for dlsetting generated by Haiyang 20080717*/
extern bool_t imu1_ir0;
extern float fd_alpha;
extern float fi_alpha;

/*define the following varables for communication with ugear by haiyang 20080508*/
extern int16_t ugear_phi;
extern int16_t ugear_psi;
extern int16_t ugear_theta;

/* added 20080522 for debugging*/
extern int16_t ugear_debug1;
extern int16_t ugear_debug2;
extern int16_t ugear_debug3;
extern int32_t ugear_debug4;
extern int32_t ugear_debug5;
extern int32_t ugear_debug6;

extern struct imu imupacket;
extern struct gps gpspacket;
extern uint8_t ugear_msg_buf[UGEAR_MAX_PAYLOAD];

extern float ins_roll_neutral;
extern float ins_pitch_neutral;
