
SRC_BOOZ=booz
SRC_BOOZ_ARCH=$(SRC_BOOZ)/arch/$(ARCH)
SRC_BOOZ_IMPL=$(SRC_BOOZ)/impl
SRC_BOOZ_ARCH_IMPL=$(SRC_BOOZ)/arch/$(ARCH)/impl
SRC_BOOZ_PERIPH=$(SRC_BOOZ)/peripherals
SRC_BOOZ_ARCH_PERIPH=$(SRC_BOOZ)/arch/$(ARCH)/peripherals
SRC_BOOZ_TEST=$(SRC_BOOZ)/test

BOOZ_INC = -I$(SRC_BOOZ) -I$(SRC_BOOZ_ARCH)
