


SRC_FIXEDWING=.
SRC_FIXEDWING_ARCH=$(SRC_FIXEDWING)/$(ARCHI)
SRC_FIXEDWING_TEST=$(SRC_FIXEDWING)/

CFG_FIXEDWING=$(PAPARAZZI_SRC)/conf/autopilot

FIXEDWING_INC = -I$(SRC_FIXEDWING) -I$(SRC_FIXEDWING_ARCH)
