#ifndef CONFIG_GORRAZOPTERE_091_H
#define CONFIG_GORRAZOPTERE_091_H

/* clock in MHz */
#define CLOCK 8

/* PPM input on mega128 ICP  */
#define PPM_DDR DDRD
#define PPM_PORT PORTD
#define PPM_PIN  PD4

#define MASTER_SPI_SS0_PIN  0
#define MASTER_SPI_SS0_PORT PORTB
#define MASTER_SPI_SS0_DDR  DDRB
#define MASTER_SPI_IT0_PIN  6
#define MASTER_SPI_IT0_PORT PORTE
#define MASTER_SPI_IT0_DDR  DDRE 
/** EINT6 */

#define MASTER_SPI_SCK_PIN  1
#define MASTER_SPI_MOSI_PIN 2
#define MASTER_SPI_MISO_PIN 3
#define MASTER_SPI_PORT PORTB
#define MASTER_SPI_DDR  DDRB

#endif /* CONFIG_GORRAZOPTERE_091_H */
