#define SLAVE_SPI_PORT   PORTB
#define SLAVE_SPI_PIN    PINB
#define SLAVE_SPI_SS_PIN 2

#define SLAVE_SPI_DDR  DDRB
#define SLAVE_SPI_MOSI_PIN 3
#define SLAVE_SPI_MISO_PIN 4
#define SLAVE_SPI_SCK_PIN  5

#define MASTER_SPI_SS0_PIN  0
#define MASTER_SPI_SS0_PORT PORTB
#define MASTER_SPI_SS0_DDR  DDRB
#define MASTER_SPI_IT0_PIN  7
#define MASTER_SPI_IT0_PORT PORTE
#define MASTER_SPI_IT0_DDR  DDRE

#define MASTER_SPI_SS1_PIN  3
#define MASTER_SPI_SS1_PORT PORTE
#define MASTER_SPI_SS1_DDR  DDRE
#define MASTER_SPI_IT1_PIN  6
#define MASTER_SPI_IT1_PORT PORTE
#define MASTER_SPI_IT1_DDR  DDRE 

#define MASTER_SPI_SS2_PIN  2
#define MASTER_SPI_SS2_PORT PORTE
#define MASTER_SPI_SS2_DDR  DDRE
#define MASTER_SPI_IT2_PIN  5
#define MASTER_SPI_IT2_PORT PORTE
#define MASTER_SPI_IT2_DDR  DDRE 


#define MASTER_SPI_SCK_PIN  1
#define MASTER_SPI_MOSI_PIN 2
#define MASTER_SPI_MISO_PIN 3
#define MASTER_SPI_PORT PORTB
#define MASTER_SPI_DDR  DDRB
