DESTDIR=/

ifeq ($(PAPARAZZI_HOME),)
PAPARAZZI_HOME=$(HOME)/paparazzi
endif

ifeq ($(PAPARAZZI_SRC),)
TOOLS=$(DESTDIR)/usr/share/paparazzi/bin
else
TOOLS=$(PAPARAZZI_SRC)/sw/tools
endif

AIRCRAFT=twinstar1

ATMELBIN = /usr/bin
ATMEL_INCLUDES = -I /usr/avr/include
ATMEL_LIBPATH = -B /usr/avr/lib/avr4 -B /usr/avr/lib/avr5
PROG_PORT = /dev/parport0

