#!/bin/sh

if [ -z $1 ] 
then
	echo "usage: sw/logalizer/getopenlog <textfile from openlog>"
elif [ $# -gt 1 ]
then
	echo "you have given to much arguments"
        echo "usage: sw/logalizer/getopenlog <textfile from openlog>"
elif [ -z $PAPARAZZI_HOME ] 
then 
	echo "\$PAPARAZZI_HOME isn't set in this shell. Please verify your environment variables!"
else
	$PAPARAZZI_HOME/sw/logalizer/openlog2tlm $1 $1.tlm
	if [ $? -eq 0 ]
	then
		$PAPARAZZI_HOME/sw/logalizer/sd2log $1.tlm
	else
		echo "openlog2tlm was not succesful. Please check for errors"
	fi
	rm $1.tlm
fi
