

#all: IvyMsgs.pm

#OCAMLC = ocamlc -I ../../lib/ocaml
#CONF_DIR = ../../../conf

#GEN_MESSAGES = ./gen_messages.out
#MESSAGES_XML = $(CONF_DIR)/messages.xml


#$(GEN_MESSAGES) : gen_messages.ml
#	$(OCAMLC) -o $@ lib.cma $<

#IvyMsgs.pm : $(MESSAGES_XML) $(GEN_MESSAGES)
#	$(GEN_MESSAGES) $< > /tmp/x.pm
#	mv /tmp/x.pm $@

clean:
	rm -f *~ 
#IvyMsgs.pm gen_messages.out *.cmo *.cmi
