#ifndef SERVOS_DIRECT_HW_H
#define SERVOS_DIRECT_HW_H

#include "LPC21xx.h"
#include "sys_time.h"

#define SERVOS_TICS_OF_USEC(s) SYS_TICS_OF_USEC(s)
#define ChopServo(x,a,b) Chop(x, a, b)

#define SERVO_REG_0 PWMMR5
#define SERVO_REG_1 PWMMR3
#define SERVO_REG_2 PWMMR1
#define SERVO_REG_3 PWMMR6
#define SERVO_REG_4 PWMMR4
#define SERVO_REG_5 PWMMR2

#define COMMAND_(i) SERVO_REG_ ## i
#define Actuator(i) COMMAND_(i)


/* 
   wiring on classix PWM connector
connector   LPC   shared         port
PWM1        PWM5  AD1_6  CAP1_3  P0.21
PWM2        PWM3  RXD0   EINT0   P0.1
PWM3        PWM1  TXD0           P0.0
PWM4        PWM6  RXD1   EINT3   P0.9
PWM5        PWM4  TXD1   AD1_1   P0.8
PWM6        PWM2  SSEL0  EINT2   P0.7

*/

#define PWM_SERVO_0_PINSEL PINSEL1 
#define PWM_SERVO_0_PINSEL_VAL 1
#define PWM_SERVO_0_PINSEL_BIT 10
#define PWM_SERVO_0_ENA PWMPCR_ENA5
#define PWM_SERVO_0_LATCH PWMLER_LATCH5

#define PWM_SERVO_1_PINSEL PINSEL0 
#define PWM_SERVO_1_PINSEL_VAL 2
#define PWM_SERVO_1_PINSEL_BIT 2
#define PWM_SERVO_1_ENA PWMPCR_ENA3
#define PWM_SERVO_1_LATCH PWMLER_LATCH3

#define PWM_SERVO_2_PINSEL PINSEL0 
#define PWM_SERVO_2_PINSEL_VAL 2
#define PWM_SERVO_2_PINSEL_BIT 0
#define PWM_SERVO_2_ENA PWMPCR_ENA1
#define PWM_SERVO_2_LATCH PWMLER_LATCH1

#define PWM_SERVO_3_PINSEL PINSEL0 
#define PWM_SERVO_3_PINSEL_VAL 2
#define PWM_SERVO_3_PINSEL_BIT 18
#define PWM_SERVO_3_ENA PWMPCR_ENA6
#define PWM_SERVO_3_LATCH PWMLER_LATCH6

#define PWM_SERVO_4_PINSEL PINSEL0 
#define PWM_SERVO_4_PINSEL_VAL 2
#define PWM_SERVO_4_PINSEL_BIT 16
#define PWM_SERVO_4_ENA PWMPCR_ENA4
#define PWM_SERVO_4_LATCH PWMLER_LATCH4

#define PWM_SERVO_5_PINSEL PINSEL0 
#define PWM_SERVO_5_PINSEL_VAL 2
#define PWM_SERVO_5_PINSEL_BIT 14
#define PWM_SERVO_5_ENA PWMPCR_ENA2
#define PWM_SERVO_5_LATCH PWMLER_LATCH2

extern const uint8_t pwm_latch_value;

#define ActuatorsCommit() { \
    PWMLER = pwm_latch_value;   \
  }

#endif /* SERVOS_DIRECT_HW_H */
