name: Docker update

on:
    push:
        branches:
        - 'master'
        paths:
        - 'docker/**'
    schedule:
        - cron: '0 3 27 * *'  # build the 27 of each month (for no particular reasons)

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Build docker images
      run: make -C docker build
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker Push dep
      run: docker push paparazziuav/pprz-dep
      
    - name: Docker Push ci
      run: docker push paparazziuav/pprz-ci
      
    - name: Docker Push dev
      run: docker push paparazziuav/pprz-dev

